---
# defaults file for mapr-metrics

# username, password and host:port for the metrics database for use with configure.sh
metrics_user: maprmetrics
metrics_password: mapr
metrics_host: "{{ groups['mysql'] | first }}"
