---
# defaults file for mapr-hive

# mysql_root_user: root
# mysql_root_password: mapr

# hive_db: metastore
# hive_db_user: hive
# hive_db_pass: mapr
# #hive_metastore_host: "{{hostvars[metrics_host].ansible_default_ipv4.address}}"
# hive_metastore_host: localhost

# hive_version: "0.12*"