---
# vars file for mapr-hive
hive_db: metastore
hive_db_user: hive
hive_db_pass: mapr
metrics_host: "{{groups['mysql'] | first}}"
hive_metastore_host: "{{ hostvars[metrics_host].ansible_default_ipv4.address }}"
