---
# tasks file for mapr-nfs

- name: install mapr-nfs packages
  yum: name={{item}} state=present
  with_items:
    - mapr-nfs

- name: is warden running?
  command: service mapr-warden status
  register: warden_status
  ignore_errors: true

- name: is NFS started?
  command: maprcli node list -filter svc==nfs -columns hn
  register: maprcli_nfs
  ignore_errors: true

- name: check whether NFS is running
  command: showmount -e localhost
  register: nfs_running
  ignore_errors: true

- name: create mountpoint for loopback NFS mountpoint
  file: path=/mapr state=directory
  when: nfs_running.rc == 0 or warden_status.rc != 0

# For each NFS server, add a local mount. Clients (such as edge nodes) will mount via system fstab.
- name: add a warden-managed local NFS mount
  template: src=mapr_fstab.j2 dest=/opt/mapr/conf/mapr_fstab mode=0644 owner=root group=root

