---
# tasks file for mapr-rh-prereqs
- name: save the current list of installed packages
  shell: rpm -qa --queryformat '%{NAME}\t%{VERSION}\n' > /root/packages_before_prereqs
  args:
    creates: /root/packages_before_prereqs

- name: test external url
  get_url: url=http://example.com dest=/dev/null 
  environment: proxy_env

- name: install libselinux-python tools
  yum: name="{{item}}" state=present
  environment: proxy_env
  with_items:
    - libselinux-python

- name: install sdparm
  yum: name=http://mirror.thelinuxfix.com/CentOS/6.5/os/x86_64/Packages/sdparm-1.04-1.1.el6.x86_64.rpm state=present
  environment: proxy_env
  when: ansible_distribution == 'Amazon'

- name: set selinux config to permissive
  selinux: state=permissive policy=targeted
  when: ansible_distribution not in ('Amazon')

- name: selinux to permissive now
  command: setenforce permissive
  when: ansible_distribution not in ('Amazon')

- name: disable iptables
  service: name=iptables state=stopped enabled=no

- name: write /etc/hosts with cluster node names
  template: src=hosts.j2 dest=/etc/hosts mode=0644 

- name: install repo for RedHat-based Linux
  template: src=maprtech.repo.j2 dest=/etc/yum.repos.d/maprtech.repo mode=0644 owner=root group=root

- name: install Java 1.7
  yum: name={{item}} state=present
  environment: proxy_env
  with_items:
    - java-1.7.0-openjdk
    - java-1.7.0-openjdk-devel

- name: install NTP
  yum: name=ntp state=present
  environment: proxy_env
  notify: restart ntp

- name: ensure NTP is enabled
  service: name=ntpd enabled=yes state=started

- name: install nfs-utils to get rpcbind
  environment: proxy_env
  yum: name=nfs-utils state=installed

- name: ensure NFS server is disabled
  service: name=nfs state=stopped enabled=no

- name: ensure rpcbind starts
  service: name=rpcbind state=started enabled=yes

- name: ensure TCP retries are set to 5
  lineinfile: dest=/etc/sysctl.conf regexp="^net.ipv4.tcp_retries2" line="net.ipv4.tcp_retries2=5"
  notify: reload sysctl

- name: disable memory overcommit
  lineinfile: dest=/etc/sysctl.conf regexp="^vm.overcommit_memory" line="vm.overcommit_memory=0"
  notify: reload sysctl

- name: create a mapr group
  group: name=mapr gid="{{mapr_gid}}"

- name: set a password for the mapr user and ensure ssh keys exist
  user: name=mapr uid="{{mapr_uid}}" group="mapr" password="{{mapr_user_pw}}" home="{{mapr_home}}" generate_ssh_key=yes state=present createhome=yes

- name: install EPEL 6 x86_64
  yum: name=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm state=installed
  environment: proxy_env
  when: ansible_distribution not in ('Amazon', 'Ubuntu')

- name: enable EPEL 6
  copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo owner=root group=root mode=0644
  when: ansible_distribution in ('Amazon')

- name: install the MapR GPG key
  command: rpm --import http://package.mapr.com/releases/pub/maprgpg.key
  environment: proxy_env

- name: save the current list of installed packages after prereqs
  shell: rpm -qa --queryformat '%{NAME}\t%{VERSION}\n' > /root/packages_after_prereqs
  args:
    creates: /root/packages_after_prereqs
