
- name: install mapr-webserver packages
  yum: name='{{item}}' state=present
  with_items:
    - mapr-webserver

- name: open port 8443 for the MCS
  command: iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport 8443 -j ACCEPT

- name: save iptables configuration
  command: service iptables save
