---
# just collecting facts so that we can locate the CLDB and mysql
- hosts: zookeepers;cldb;mysql;nfs

- hosts: edge
  sudo: yes
  roles:
    - mapr-redhat-prereqs
    - { role: mapr-client,
        cluster_name: '{{mapr_cluster_name}}' }
