---
- hosts: all
  max_fail_percentage: 0
  tasks:
    - group_by: key={{ansible_virtualization_type}}
    - group_by: key={{ansible_distribution}}

- hosts: CentOS;RedHat;Amazon
  max_fail_percentage: 0
  sudo: yes
  roles:
    - { role: mapr-redhat-prereqs,
        mapr_user_pw: '$1$RK1O7/4r$2Ff/OWxXibays7JWsBBaf1',
        mapr_uid: 2147483632,
        mapr_gid: 2147483632,
        mapr_home: '/home/mapr' }
    - python-lxml

- hosts: Ubuntu;Debian
  max_fail_percentage: 0
  sudo: yes
  roles:
    - { role: mapr-debian-prereqs,
        mapr_user_pw: '$1$yoPLWBQ6$6fvQchDTBu3Ccs3PVURpA.',
        mapr_uid: 2147483632,
        mapr_gid: 2147483632,
        mapr_home: '/home/mapr' }
